FROM golang:1.26-alpine AS builder

ARG VERSION
ARG GIT_SHA
ARG BUILD_TIME

WORKDIR /src

COPY cmd/api/go.mod cmd/api/go.sum ./
RUN go mod download

COPY cmd/api/*.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w -X main.Version=${VERSION} -X main.GitSHA=${GIT_SHA} -X main.BuildTime=${BUILD_TIME}" -o api-server
